// <auto-generated />
using System;
using AgriVision.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgriVision.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgriVision.Domain.Entities.Disease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Prevention")
                        .HasColumnType("text")
                        .HasColumnName("prevention");

                    b.Property<string>("Symptoms")
                        .HasColumnType("text")
                        .HasColumnName("symptoms");

                    b.Property<string>("Treatment")
                        .HasColumnType("text")
                        .HasColumnName("treatment");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VietnameseName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("vietnamese_name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_diseases_name");

                    b.ToTable("diseases", (string)null);
                });

            modelBuilder.Entity("AgriVision.Domain.Entities.Plant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("ScientificName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("scientific_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VietnameseName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("vietnamese_name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_plants_name");

                    b.ToTable("plants", (string)null);
                });

            modelBuilder.Entity("AgriVision.Domain.Entities.PlantDisease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ClassIndex")
                        .HasColumnType("integer")
                        .HasColumnName("class_index");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("class_name");

                    b.Property<Guid>("DiseaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("disease_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Guid>("PlantId")
                        .HasColumnType("uuid")
                        .HasColumnName("plant_id");

                    b.HasKey("Id");

                    b.HasIndex("ClassIndex")
                        .IsUnique()
                        .HasDatabaseName("ix_plant_diseases_class_index");

                    b.HasIndex("DiseaseId")
                        .HasDatabaseName("ix_plant_diseases_disease_id");

                    b.HasIndex("PlantId")
                        .HasDatabaseName("ix_plant_diseases_plant_id");

                    b.HasIndex("PlantId", "DiseaseId")
                        .IsUnique()
                        .HasDatabaseName("ix_plant_diseases_plant_id_disease_id");

                    b.ToTable("plant_diseases", null, t =>
                        {
                            t.HasCheckConstraint("ck_plant_diseases_class_index", "class_index >= 0");
                        });
                });

            modelBuilder.Entity("AgriVision.Domain.Entities.Prediction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_path");

                    b.Property<string>("ImagePublicId")
                        .HasColumnType("text")
                        .HasColumnName("image_public_id");

                    b.Property<Guid>("PredictedPlantDiseaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("predicted_plant_disease_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_predictions_created_at");

                    b.HasIndex("PredictedPlantDiseaseId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_predictions_user_id");

                    b.ToTable("predictions", (string)null);
                });

            modelBuilder.Entity("AgriVision.Domain.Entities.PredictionDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("PlantDiseaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("plant_disease_id");

                    b.Property<Guid>("PredictionId")
                        .HasColumnType("uuid")
                        .HasColumnName("prediction_id");

                    b.Property<double>("Probability")
                        .HasColumnType("double precision")
                        .HasColumnName("probability");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.HasKey("Id");

                    b.HasIndex("PlantDiseaseId");

                    b.HasIndex("PredictionId")
                        .HasDatabaseName("ix_prediction_details_prediction_id");

                    b.HasIndex("PredictionId", "Rank")
                        .IsUnique()
                        .HasDatabaseName("ix_prediction_details_prediction_id_rank");

                    b.ToTable("prediction_details", null, t =>
                        {
                            t.HasCheckConstraint("ck_prediction_details_rank", "rank > 0");
                        });
                });

            modelBuilder.Entity("AgriVision.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("User")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("AgriVision.Domain.Entities.PlantDisease", b =>
                {
                    b.HasOne("AgriVision.Domain.Entities.Disease", "Disease")
                        .WithMany("PlantDiseases")
                        .HasForeignKey("DiseaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgriVision.Domain.Entities.Plant", "Plant")
                        .WithMany("PlantDiseases")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Disease");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("AgriVision.Domain.Entities.Prediction", b =>
                {
                    b.HasOne("AgriVision.Domain.Entities.PlantDisease", "PredictedPlantDisease")
                        .WithMany("Predictions")
                        .HasForeignKey("PredictedPlantDiseaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgriVision.Domain.Entities.User", "User")
                        .WithMany("Predictions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PredictedPlantDisease");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgriVision.Domain.Entities.PredictionDetail", b =>
                {
                    b.HasOne("AgriVision.Domain.Entities.PlantDisease", "PlantDisease")
                        .WithMany("PredictionDetails")
                        .HasForeignKey("PlantDiseaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgriVision.Domain.Entities.Prediction", "Prediction")
                        .WithMany("PredictionDetails")
                        .HasForeignKey("PredictionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlantDisease");

                    b.Navigation("Prediction");
                });

            modelBuilder.Entity("AgriVision.Domain.Entities.Disease", b =>
                {
                    b.Navigation("PlantDiseases");
                });

            modelBuilder.Entity("AgriVision.Domain.Entities.Plant", b =>
                {
                    b.Navigation("PlantDiseases");
                });

            modelBuilder.Entity("AgriVision.Domain.Entities.PlantDisease", b =>
                {
                    b.Navigation("PredictionDetails");

                    b.Navigation("Predictions");
                });

            modelBuilder.Entity("AgriVision.Domain.Entities.Prediction", b =>
                {
                    b.Navigation("PredictionDetails");
                });

            modelBuilder.Entity("AgriVision.Domain.Entities.User", b =>
                {
                    b.Navigation("Predictions");
                });
#pragma warning restore 612, 618
        }
    }
}
